### ISSUE TITLE
Is the Solid OIDC spec too strict on aud claim?

### ISSUE THREAD

**Issue by matthieubosquet** [solid/authentication-panel#135]
The Solid OIDC spec currently says: "The audience claim MUST be the string solid.".

See: https://solid.github.io/authentication-panel/solid-oidc/#tokens-access

Is there a Use Case for allowing JWTs with multiple audience values?

See also: https://github.com/solid/identity-token-verifier/issues/3

**Comment by acoburn** [comment]
@matthieubosquet thanks for raising this. Here is some useful context.

From [RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.3), which defines JWT

```
4.1.3.  "aud" (Audience) Claim

   The "aud" (audience) claim identifies the recipients that the JWT is
   intended for.  Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.  In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.  The
   interpretation of audience values is generally application specific.
   Use of this claim is OPTIONAL.
```

From [Open ID Connect 1.0](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) -- note that this is specifically about the ID token, not the access token

```
aud
    REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain
    the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also
    contain identifiers for other audiences. In the general case, the aud value is
    an array of case sensitive strings. In the common special case when there is
    one audience, the aud value MAY be a single case sensitive string.
```

In both cases it is significant (to me) that the audience claim can be either an array or a single string. In the context of this specification, we have complete control over the definition of and requirements for an access token, so it would be possible to take either approach. That is: (a) restrict the audience to a single string or (b) allow multiple audience values.

I would argue that if Solid-OIDC chooses to be more strict than these other specifications, that would be fine, but we should have a very clear and compelling reason to do so. My perspective is that there is not a clear and compelling reason to be more strict and there seem to be [use cases](https://github.com/solid/identity-token-verifier/issues/3#issue-813839835) for allowing multiple `aud` values. Am I missing some considerations here? Are there other perspectives on this?

**Comment by matthieubosquet** [comment]
I would just be worried that a non-solid audience could be perceived as just OIDC and skip checking the WebID's `solid:oidcIssuer`, which might be valid as long as the audience is under the same authority as the issuer and the WebID has been verified when the account was created. Does it make sense?

**Comment by acoburn** [comment]
> I would just be worried that a non-solid audience could be perceived as just OIDC

I would see this more as a feature than a problem. Consider the following:

An organization has an existing SSO system, built on OIDC, used by many non-Solid apps. Now they want to extend their identity provider to also support Solid apps. They can do this by adding a WebID claim and by adding `solid` to a list of existing audience claims. This allows that organization to continue to use the same IdP for both Solid and non-Solid applications.

This is something that we not only should support but also encourage. Otherwise, we will be forcing organizations to adopt a parallel identity system just for Solid, which could make adoption that much harder.

In any case, all Solid resource servers [MUST verify](https://solid.github.io/authentication-panel/solid-oidc/#resource-access-validation) the WebID claim if the issuer claim is a different domain than the WebID, but that is orthogonal to the audience claim, which must also be validated. Having multiple audiences is mostly relevant in SSO environments where the IdP is separate from the domain of the WebID and/or the resource server.

**Comment by matthieubosquet** [comment]
This all makes sense. I created a PR potentially fixing the issue. I think what you're describing is a clear use case.

https://github.com/solid/authentication-panel/pull/141
