### ISSUE TITLE
Caching IdP public keys

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#58]
I might be wrong about this, but wouldn't recommending the caching of public keys as stated here:

    It is RECOMMENDED that the RS keep a list of trusted IdPs, to facilitate the expedient lookup of JWKS through local trust stores or cached public keys.

Be an anti-pattern as it would be recommended that IdPs rotate their keys frequently?

**Comment by elf-pavlik** [comment]
I think RS could track *exp* claim on access tokens signed with given key and extend caching that based on that *exp* date. IdP should not remove key as long as valid tokens exist signed by that key so caching it based on *exp* claim in those tokens seems reasonable.

**Comment by acoburn** [comment]
Caching should not be a problem. In fact, it should be encouraged.

That said, there are better and worse ways to handle cache invalidation. When an IdP key is rotated, it is important that the new key has a new (unique) identifier `kid`. This way, if the incoming JWT has a `kid` value that is not present in the cached JWKS, the resource service can attempt to refresh the cached JWKS data; otherwise, it can simply use the cached value.

**Comment by acoburn** [comment]
This issue has been in the `can-be-closed?` state for over a month with no objections.
