### ISSUE TITLE
HTTP requests don't contain hashes

### ISSUE THREAD

**Issue by bblfish** [solid/authentication-panel#96]
In the [current published primer spec](https://solid.github.io/authentication-panel/solid-oidc-primer/#pkce-login-flow-step-7) there is a request for 

```
GET https://decentphotos.example/webid#this
```

HTTP Requests MUST NOT contain "#fragments", as the HTTP is a protocol to retrieve documents, not document fragments.

**Comment by elf-pavlik** [comment]
could you please make PR to fix it?

**Comment by TallTed** [comment]
Problem line in source [is here](https://github.com/solid/authentication-panel/blob/24a93643fc8a224465631e5e77f0b847cc06516f/proposals/solid-oidc-primer/index.bs#L283).  I'll leave the PR to you.

**Comment by acoburn** [comment]
True, the HTTP request should not contain a `#fragment`, but that fragment portion is also an important part of the client's WebID, since that will affect the triple that is matched in the RDF response. So it would likely make sense to have something like, "For the WebID `https://decentphotos.example/webid#this`, make a request `GET https://decentphotos.example/webid` ..."
